---
- name: Install mariadb
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_packages: "{{ mariadb_packages }}"

- name: Pause for 1 minute
  ansible.builtin.pause:
    minutes: 1
