---
- name: Copy key
  become: true
  ansible.builtin.get_url:
    url: "{{ mariadb_key_url }}"
    checksum: "sha256:{{ mariadb_key_url }}.sha256"
    dest: "{{ mariadb_key_path }}/{{ mariadb_key_name }}"
    force: true

- name: Install mariadb
  ansible.builtin.import_role:  
    name: ansible-role-installer
  vars:
    installer_repositories:
      - "deb [arch=amd64,arm64,signed-by={{ mariadb_key_path }}{{ mariadb_key_name }}] https://dlm.mariadb.com/repo/mariadb-server/{{ mariadb_version }}/repo/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
      - "deb [arch=amd64,arm64,signed-by={{ mariadb_key_path }}{{ mariadb_key_name }}] https://dlm.mariadb.com/repo/mariadb-server/{{ mariadb_version }}/repo/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main/debug"
    installer_packages: "{{ mariadb_packages }}"
