---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ mariadb_autoremove }}"
    purge: "{{ mariadb_purge }}"
    state: absent
  loop: "{{ mariadb_packages }}"

- name: Ensure that repositories are uninstalled
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    update_cache: true
    state: absent
  loop: "{{ mariadb_repositories }}"

- name: Remove key
  become: true
  ansible.builtin.file:
    path: "{{ mariadb_key_path }}/{{ mariadb_key_name }}"
    state: absent
